#!/bin/zsh
#
# tag a set of mp3 files that share the same artist and album
#
# dependencies:
#     awk
#     flac
#     mid3v2
#     sed
#     zsh
#     zsh/mapfile
#
#-------------------------------------------------------------------------------------------------------
# mid3v2: https://github.com/dhamaniasad/mutagen/blob/master/tools/mid3v2
# Vorbis tags used by FLAC: https://exiftool.org/TagNames/Vorbis.html
#-------------------------------------------------------------------------------------------------------

function usage() {
    echo "Usage:"
    echo ""
    echo "\ttag-album artist album recording_date"
    echo ""
    echo "Execute this script in the same directory as an album_titles.txt file"
    echo ""
    echo "album_titles.txt should be an ASCII or UTF-8 text file, where each line"
    echo "contains the filename followed by a pipe ('|') and then the track title."
    echo ""
    echo "You can include additional spaces around the pipe for better"
    echo "readability; the spaces won't be included in the tags."
    echo ""
    echo "path/name_of_file   ,   track_title"
    echo "Lines starting with '#' (comments) are ignored."
    echo ""
    }

NUM_ARGS=$#

if [[ ! $NUM_ARGS == 3 ]];
then
    echo -e "\n>>> ERROR >>> Incorrect arguments!\n"
    usage
    exit 1
fi

ARTIST=$1
ALBUM=$2
RECORDING_YEAR=$3

zmodload zsh/mapfile
TITLES_FILE=./album_titles.txt

if [[ ! -f "$TITLES_FILE" ]];
then
    echo -e "\n>>> ERROR >>> $TITLES_FILE not found!\n"
    usage
    exit 1
fi

FLINES=( "${(f)mapfile[$TITLES_FILE]}" )
LIST="${mapfile[$TITLES_FILE]}"

# get total number of files
integer t=0
for line in $FLINES; do
    if [[ $line == \#* ]];
    then
        continue
    fi
    (( t++ ))
done

TOTAL_COUNT=$t
echo "TOTAL_COUNT=$TOTAL_COUNT"

t=0
for line in $FLINES; do
    if [[ $line == \#* ]];
    then
        continue
    fi
    (( t++ ))
    fields=(${(@s:|:)line})

    filename=`echo ${fields[1]} | awk '{ sub(/^[ \t]+/, ""); print }'`
    
    title=`echo ${fields[2]} | awk '{ sub(/^[ \t]+/, ""); print }'`

    echo "title=$title"
    
    if [[ $filename == *.mp3 ||  $filename == *.m4a ]];
    then
        /usr/bin/mid3v2 \
            -t "${title}" \
            -T \"$t/${TOTAL_COUNT}\" \
            -a \"${ARTIST}\" \
            -A \"${ALBUM}\" \
            -y ${RECORDING_YEAR} \
            "${filename}"
    else
        if [[ $filename == *.flac ]];
        then
            /usr/bin/flac -f \
                          --tag="TITLE=${title}" \
                          --tag="TRACKNUMBER=${t}" \
                          --tag="ARTIST=${ARTIST}" \
                          --tag="ALBUM=${ALBUM}" \
                          --tag="DATE=${RECORDING_YEAR}" \
                          "${filename}"
        fi
    fi
done
